Repository adoptium/aqa-test-tools, pull requests merged in 2021-06, with the labels that each got.

#323 delete forever builds if the whole pipeline is deleted
  TestResultSummaryService/BuildMonitor.js
  TestResultSummaryService/routes/deleteBuildData.js
Labels: bug

#422 GitHub Data Collection for DeepAQAtik
  MachineLearningPrototype/dataCollection/collect_data.py
Labels: enhancement

#406 fix jdkDate parser
  TestResultSummaryService/parsers/Parser.js
  TestResultSummaryService/routes/getTabularData.js
  test-result-summary-client/src/Dashboard/Widgets/Graph/Dacapo.jsx
  test-result-summary-client/src/Dashboard/Widgets/Graph/utils.js
  test-result-summary-client/src/TabularView/TabularView.jsx
Labels: bug

#450 Revert "fix jdkDate parser"
  TestResultSummaryService/parsers/Parser.js
  TestResultSummaryService/routes/getTabularData.js
  test-result-summary-client/src/Dashboard/Widgets/Graph/Dacapo.jsx
  test-result-summary-client/src/Dashboard/Widgets/Graph/utils.js
  test-result-summary-client/src/TabularView/TabularView.jsx
Labels: bug

#451 Update trssml link
  MachineLearningPrototype/DLGitIssuesAnalysis.ipynb
  test-result-summary-client/src/Build/PossibleIssues.jsx
Labels: deepAQAtik, enhancement

#473 Add Junit test report link
  test-result-summary-client/src/Build/DeepHistory.jsx
Labels: enhancement
